// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQiLygP0vgc0sL1dtGAshdGELAB9rL9hY',
    appId: '1:86004782132:web:4794f7614b542bc56fa661',
    messagingSenderId: '86004782132',
    projectId: 'proyectoprogramacionmovi-c9fee',
    authDomain: 'proyectoprogramacionmovi-c9fee.firebaseapp.com',
    storageBucket: 'proyectoprogramacionmovi-c9fee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDLd6xr3pvkPMSpbzzEYxiUzNpgxkwZ4',
    appId: '1:86004782132:android:b5827bf47f6f1a0a6fa661',
    messagingSenderId: '86004782132',
    projectId: 'proyectoprogramacionmovi-c9fee',
    storageBucket: 'proyectoprogramacionmovi-c9fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWaw-44vAlNm-YTCZ_J06qjbFBRAFCo-g',
    appId: '1:86004782132:ios:0396eb5b1f46b03f6fa661',
    messagingSenderId: '86004782132',
    projectId: 'proyectoprogramacionmovi-c9fee',
    storageBucket: 'proyectoprogramacionmovi-c9fee.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWaw-44vAlNm-YTCZ_J06qjbFBRAFCo-g',
    appId: '1:86004782132:ios:62e1f38c9a5b2f1b6fa661',
    messagingSenderId: '86004782132',
    projectId: 'proyectoprogramacionmovi-c9fee',
    storageBucket: 'proyectoprogramacionmovi-c9fee.appspot.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
